services:
  # database
  db:
    image: mariadb:10.8
    environment:
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql 

  # database administration - http://localhost:8080
  phpmyadmin:
      image: phpmyadmin
      depends_on:
        - db
      ports:
        - 8080:80
      environment:
        PMA_HOST: db
        PMA_USER: exampleuser
        PMA_PASSWORD: examplepass           

  # redis for object caching
  redis:
      image: redis:7
      ports:
        - 6379:6379
      command: redis-server --save 60 1 --loglevel warning --requirepass redispass
      volumes:
        - redis:/data      

  # wordpress - http://localhost
  wordpress:
    image: wordpress:6-php8.1-apache
    depends_on:
      - db
      - redis
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
        define( 'WP_REDIS_PASSWORD', 'redispass' );
    volumes:
      - wordpress:/var/www/html

  wordpress_cli:
    depends_on:
      - wordpress
    image: wordpress:cli-php8.1
    user: 33:33
    command: tail -f /dev/null
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb 

volumes:
  wordpress:
  db:
  redis: